server:
  port: 8089
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  application:
    name: "Rennnhong-Backend-StarterKit"
  datasource:
    #    url: jdbc:h2:mem:testdb
    url: jdbc:sqlserver://127.0.0.1;databaseName=tdjw_test_jpa
    #    driver-class-name: org.h2.Driver
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: rayluo
    password: 1938
  #    sql-script-encoding: utf-8
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    database: sql_server
    #    database: H2
    properties:
      hibernate:
    #        use_nationalized_character_data: true # 設定 Database--這不知道是殺小，加的話會報「不支持從 varchar 到 NCHAR 的轉換」的錯誤
    hibernate:
      ddl-auto: create-drop
  security:
    user:
      name: admin
      password: test
logging:
  level:
    root: warn
    com.kangdainfo: debug
  file:
    name: ./target/logs/${spring.application.name}
